# Markdownlint Configuration
# https://github.com/DavidAnson/markdownlint
#
# This configuration works with:
# - pre-commit (markdownlint-cli)
# - GitHub Super-Linter
# - VS Code markdownlint extension
#
# Rule reference: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
#
# ============================================================================
# PRE-COMMIT SETUP
# ============================================================================
# Add the following to your .pre-commit-config.yaml:
#
#   - repo: https://github.com/igorshubovych/markdownlint-cli
#     rev: v0.43.0  # Use latest stable version
#     hooks:
#       - id: markdownlint
#         name: MarkdownLint
#         entry: markdownlint
#         language: node
#         files: '\.md$'
#
# The hook will automatically detect .markdownlint.yaml in the repo root.
# To specify a custom config path, add args:
#         args: ['--config', '.markdownlint.yaml']
#
# ============================================================================
# GITHUB SUPER-LINTER SETUP
# ============================================================================
# Super-Linter automatically detects .markdownlint.yaml in the repo root.
#
# In your GitHub Actions workflow (.github/workflows/linter.yml):
#
#   - name: Super-Linter
#     uses: super-linter/super-linter@v5
#     env:
#       VALIDATE_MARKDOWN: true
#       # Optional: specify config path (default: .markdownlint.yaml)
#       MARKDOWN_CONFIG_FILE: .markdownlint.yaml
#       # Optional: disable specific linters
#       VALIDATE_JSCPD: false
#
# Supported config filenames (in order of precedence):
#   - .markdownlint.yaml
#   - .markdownlint.yml
#   - .markdownlint.json
#   - .markdownlint.jsonc
#   - .markdownlintrc
#
# ============================================================================

---
# Enable all rules by default
default: true

# MD013 - Line length
# Relaxed to 120 chars for readability; disabled for code blocks, tables, and headings
# which often need longer lines for clarity
MD013:
  line_length: 88
  code_blocks: false
  tables: false
  headings: false

# MD024 - Multiple headings with the same content
# Allow duplicate headings if they are not siblings (e.g., "## Usage" under different sections)
MD024:
  siblings_only: true

# MD033 - Inline HTML
# Allow specific HTML elements commonly used in GitHub markdown
# br: line breaks, details/summary: collapsible sections, sup/sub: superscript/subscript
MD033:
  allowed_elements:
    - br
    - details
    - summary
    - sup
    - sub

# MD040 - Fenced code blocks should have a language specified
# Disabled: not all code blocks need syntax highlighting (e.g., plain text output)
MD040: false

# MD041 - First line in file should be a top-level heading
# Disabled: allows for badges, shields, or front matter before the title
MD041: false
