#!/bin/sh
# packages.sh — Health check: verifies all installed packages are up to date.
#
# Pass (exit 0): all installed packages are current.
# Fail (exit 1): one or more packages have available updates.
#
# This script cleans up any temporary cache created during its execution
# to keep the container image as small as possible.

# Refresh the package index to detect available updates
if ! apt-get update -qq 2>/dev/null; then
    echo "packages-check: failed to update package index"
    exit 1
fi

# Simulate upgrade to check for outdated packages — no actual changes made
UPGRADE_OUTPUT=$(apt-get -s upgrade 2>/dev/null)

# Always clean up apt lists generated by this run to keep the image thin
rm -rf /var/lib/apt/lists/*

# Parse count of packages that can be upgraded
# Typical output line: "0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded."
UPGRADEABLE=$(echo "$UPGRADE_OUTPUT" | grep -E "^[0-9]+ upgraded" | awk '{print $1}')

if [ -z "$UPGRADEABLE" ]; then
    echo "packages-check: failed to parse upgrade output"
    exit 1
fi

if [ "$UPGRADEABLE" -eq 0 ]; then
    echo "packages-check: all packages are up to date"
    exit 0
fi

# List each package that has an available update before failing
echo "packages-check: $UPGRADEABLE package(s) have updates available:"
echo "$UPGRADE_OUTPUT" | grep "^Inst " | awk '{print "  " $2}'
exit 1
